apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # Port you want to expose externally
      targetPort: 3000  # Port your application is listening on
  type: NodePort